#!/bin/sh

cat << EOHEADER
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Test plantuml-syntax</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="style.css" type="text/css" />
    <style>
      body {
        background-color: #CCC;
        font-size: 14pt;
        font-family: arial, sans-serif;
      }
      figure {
        margin-left: 1em;
        flex: 1 0 0;
        overflow: auto;
      }
      h1, h2 {
        color: #AAA;
        text-align: center;
      }
      h2 {
        font-size: 140%;
        margin: 1em 2em;
      }
      a {
        text-decoration: none;
        color: #58C;
      }
      li {
        list-style-type: none;
      }
      .wrap {
        display: flex;
        min-height: 100dvh;
        margin: 0 auto;
      }
      .two {
        display: flex;
        gap: 1em;
        overflow: auto;
      }
      svg {
        width: 240%;
        height: 240%;
      }
      section {
        margin: 1em;
        padding: 1em;
        flex: 1 0 0;
        width: fit-content;
      }
      nav {
        position: sticky;
        top: 0;
        height: 100dvh;
        overflow-y: auto;
        background-color: #CCC;
        padding: 1em;
        min-width: 30%;
        max-width: 300px;
        font-size: 16pt;
      }
      nav > ul {
        position: relative;
        top: 0;
      }
EOHEADER

echo "/* Styles from vim */"
cat uml/*.css | sort -u

cat << "EOREST";
    </style>
  </head>
  <body>
  <h1>PlantUML syntax examples</h1>
  <p>These are examples taken from the official documentation: https://plantuml.com/

  Generated by <a href="https://github.com/aklt/plantuml-syntax-test">Plantuml syntax Test</a>.
  </p>
EOREST

echo '<div class="wrap">'
echo "<nav><ul>"
for i in $(echo "$@" | tr ' ' '\n' | sort); do
  baseName=$(echo "$i" | sed -e 's/^uml\///' -e 's/\.pre\.html$//')
  titleName=$(echo "$baseName" | sed -e 's/^uml\///' -e 's/^reference_//' -e 's/_/ /g')
  echo "<li><a href=\"#$baseName\">$titleName</a></li>"
done
echo "</ul></nav>"

echo "<main>"
for i in $(echo "$@" | tr ' ' '\n' | sort); do
  baseName=$(echo "$i" | sed -e 's/\.pre\.html$//')
  anchorName=$(echo "$baseName" | sed -e 's/^uml\///')
  titleName=$(echo "$baseName" | sed -e 's/^uml\///' -e 's/^reference_//' -e 's/_/ /g')
  echo "<a name=\"$anchorName\"></a><section>"
  echo "<h2>$titleName</h2>"
  echo '<div class="two">'
  cat "$i" | sed -e "s/ id='vimCodeElement'//"
  echo "<figure>"
  cat "${baseName}.svg" | sed -e 's/^<?xml version="1.0" encoding="us-ascii" standalone="no"?>//'
  echo "</figure>"
  echo "</div></section>"
done
echo "</main>"
echo "</div>"

cat << EOFOOTER
  </body>
</html>
EOFOOTER


